framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 2
                    multiplier: 2
                    max_delay: 5000
            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\Messages\TransactionMessage: async
            App\Messages\UpdateCoinPriceMessage: async
            App\Messages\LoadCoinBySymbolMessage: async
