<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711133742 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Изменение сущности монет, расширение информации о монете';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE coin_contract (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contract_address VARCHAR(255) NOT NULL, network VARCHAR(50) NOT NULL, local_price DOUBLE PRECISION DEFAULT NULL, decimal INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, coin_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_237AE68284BBDA7 ON coin_contract (coin_id)');
        $this->addSql('CREATE TABLE coin_detail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, investors JSON DEFAULT NULL, market_cap NUMERIC(24, 10) NOT NULL, liquidity NUMERIC(24, 10) NOT NULL, volume NUMERIC(22, 10) NOT NULL, total_supply NUMERIC(14, 0) NOT NULL, circulation_supply NUMERIC(24, 10) NOT NULL, max_supply NUMERIC(14, 0) NOT NULL, listed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, coin_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FDA5DC3084BBDA7 ON coin_detail (coin_id)');
        $this->addSql('ALTER TABLE coin_contract ADD CONSTRAINT FK_237AE68284BBDA7 FOREIGN KEY (coin_id) REFERENCES coin (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_COINTCONTRACT_CONTRACTADDRESS_NETWORK ON coin_contract (contract_address, network)');
        $this->addSql('ALTER TABLE coin_detail ADD CONSTRAINT FK_FDA5DC3084BBDA7 FOREIGN KEY (coin_id) REFERENCES coin (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coin DROP contract_address');
        $this->addSql('ALTER TABLE coin DROP network');
        $this->addSql('ALTER TABLE coin DROP "decimal"');
        $this->addSql('ALTER TABLE coin RENAME COLUMN price TO avg_price');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE coin_contract DROP CONSTRAINT FK_237AE68284BBDA7');
        $this->addSql('ALTER TABLE coin_detail DROP CONSTRAINT FK_FDA5DC3084BBDA7');
        $this->addSql('DROP TABLE coin_contract');
        $this->addSql('DROP TABLE coin_detail');
        $this->addSql('ALTER TABLE coin ADD contract_address VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE coin ADD network VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE coin ADD "decimal" INT NOT NULL');
        $this->addSql('ALTER TABLE coin RENAME COLUMN avg_price TO price');
    }
}
