<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260524200035 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Добавлены транзакции, кошельки, правка coin_link';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, price NUMERIC(28, 8) NOT NULL, qty NUMERIC(28, 8) NOT NULL, gas NUMERIC(28, 8) NOT NULL, fee NUMERIC(28, 8) NOT NULL, tx_hash VARCHAR(128) DEFAULT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wallet_id INT NOT NULL, user_id INT NOT NULL, coin_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D1712520F3 ON transaction (wallet_id)');
        $this->addSql('CREATE INDEX IDX_723705D1A76ED395 ON transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_723705D184BBDA7 ON transaction (coin_id)');
        $this->addSql('CREATE TABLE wallet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty NUMERIC(28, 8) NOT NULL, price_avg NUMERIC(28, 8) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, coin_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7C68921FA76ED395 ON wallet (user_id)');
        $this->addSql('CREATE INDEX IDX_7C68921F84BBDA7 ON wallet (coin_id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1712520F3 FOREIGN KEY (wallet_id) REFERENCES wallet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D184BBDA7 FOREIGN KEY (coin_id) REFERENCES coin (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921F84BBDA7 FOREIGN KEY (coin_id) REFERENCES coin (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coin_link DROP CONSTRAINT fk_b57623384bbda7');
        $this->addSql('ALTER TABLE coin_link ADD type VARCHAR(32) NOT NULL');
        $this->addSql('ALTER TABLE coin_link ADD url VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE coin_link DROP name');
        $this->addSql('ALTER TABLE coin_link ADD CONSTRAINT FK_B57623384BBDA7 FOREIGN KEY (coin_id) REFERENCES coin (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1712520F3');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1A76ED395');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D184BBDA7');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT FK_7C68921FA76ED395');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT FK_7C68921F84BBDA7');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE wallet');
        $this->addSql('ALTER TABLE coin_link DROP CONSTRAINT FK_B57623384BBDA7');
        $this->addSql('ALTER TABLE coin_link ADD name VARCHAR(64) NOT NULL');
        $this->addSql('ALTER TABLE coin_link DROP type');
        $this->addSql('ALTER TABLE coin_link DROP url');
        $this->addSql('ALTER TABLE coin_link ADD CONSTRAINT fk_b57623384bbda7 FOREIGN KEY (coin_id) REFERENCES coin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
