<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260523114351 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE coin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, symbol VARCHAR(20) NOT NULL, name VARCHAR(64) NOT NULL, price DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE coin_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, coin_id INT NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B57623384BBDA7 ON coin_link (coin_id)');
        $this->addSql('ALTER TABLE coin_link ADD CONSTRAINT FK_B57623384BBDA7 FOREIGN KEY (coin_id) REFERENCES coin (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE coin_link DROP CONSTRAINT FK_B57623384BBDA7');
        $this->addSql('DROP TABLE coin');
        $this->addSql('DROP TABLE coin_link');
    }
}
