<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723181214 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create refresh_tokens and fix coin_detail';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE refresh_tokens (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            token_hash CHAR(64) NOT NULL,
            device_fingerprint VARCHAR(255) NOT NULL,
            ip_address VARCHAR(39) NOT NULL,
            is_revoked BOOLEAN DEFAULT FALSE NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            expired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (token_hash)');
        $this->addSql('CREATE INDEX IDX_9BACE7E19D86650F ON refresh_tokens (user_id)');
        $this->addSql('ALTER TABLE refresh_tokens ADD CONSTRAINT FK_9BACE7E19D86650F FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coin_detail ALTER market_cap TYPE NUMERIC(18, 4)');
        $this->addSql('ALTER TABLE coin_detail ALTER total_supply TYPE NUMERIC(16, 4)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE refresh_tokens DROP CONSTRAINT FK_9BACE7E19D86650F');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('ALTER TABLE coin_detail ALTER market_cap TYPE NUMERIC(24, 4)');
        $this->addSql('ALTER TABLE coin_detail ALTER total_supply TYPE NUMERIC(16, 0)');
    }
}
