<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611195149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create table wallet_coin, update tables wallet and transaction ';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE wallet_coin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, balance NUMERIC(36, 18) NOT NULL, avg_price NUMERIC(36,18) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wallet_id INT NOT NULL, coin_id INT NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE INDEX IDX_38FB6258712520F3 ON wallet_coin (wallet_id)');
        $this->addSql('CREATE INDEX IDX_38FB625884BBDA7 ON wallet_coin (coin_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_38FB6258712520F384BBDA7 ON wallet_coin (wallet_id, coin_id)');
        $this->addSql('ALTER TABLE wallet_coin ADD CONSTRAINT FK_38FB6258712520F3 FOREIGN KEY (wallet_id) REFERENCES wallet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wallet_coin ADD CONSTRAINT FK_38FB625884BBDA7 FOREIGN KEY (coin_id) REFERENCES coin (id) NOT DEFERRABLE');

        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT fk_723705d1a76ed395');
        $this->addSql('DROP INDEX idx_723705d1a76ed395');
        $this->addSql('ALTER TABLE transaction DROP user_id');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT fk_7c68921fa76ed395');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT fk_7c68921f84bbda7');
        $this->addSql('DROP INDEX idx_7c68921f84bbda7');
        $this->addSql('DROP INDEX idx_7c68921fa76ed395');
        $this->addSql('ALTER TABLE wallet ADD address VARCHAR(64) NOT NULL');
        $this->addSql('ALTER TABLE wallet DROP created_at');
        $this->addSql('ALTER TABLE wallet DROP updated_at');
        $this->addSql('ALTER TABLE wallet DROP user_id');
        $this->addSql('ALTER TABLE wallet DROP coin_id');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7C68921FD4E6F81 ON wallet (address)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE wallet_coin DROP CONSTRAINT FK_38FB6258712520F3');
        $this->addSql('ALTER TABLE wallet_coin DROP CONSTRAINT FK_38FB625884BBDA7');
        $this->addSql('DROP TABLE wallet_coin');
        $this->addSql('ALTER TABLE transaction ADD user_id INT NOT NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT fk_723705d1a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_723705d1a76ed395 ON transaction (user_id)');
        $this->addSql('DROP INDEX UNIQ_7C68921FD4E6F81');
        $this->addSql('ALTER TABLE wallet ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE wallet ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE wallet ADD user_id INT NOT NULL');
        $this->addSql('ALTER TABLE wallet ADD coin_id INT NOT NULL');
        $this->addSql('ALTER TABLE wallet DROP address');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT fk_7c68921fa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT fk_7c68921f84bbda7 FOREIGN KEY (coin_id) REFERENCES coin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_7c68921f84bbda7 ON wallet (coin_id)');
        $this->addSql('CREATE INDEX idx_7c68921fa76ed395 ON wallet (user_id)');
    }
}
