parameters:
    listing.limit: 20
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    App\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 100 }

    App\MessageHandler\CoinPriceHandler:
        arguments:
            $apiServiceProviders:
                ALCHEMY: '@App\Service\External\Alchemy\PriceService'
                COINGECKO: '@App\Service\External\CoinGecko\PriceService'
