parameters:
    listing.limit: 20
services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    App\OpenApi\OpenApiSpec: ~

#    App\MessageHandler\CoinPriceHandler:
#        arguments:
#            $apiServiceProviders:
#                ALCHEMY: '@App\Service\External\Alchemy\PriceService'
#                COINGECKO: '@App\Service\External\CoinGecko\PriceService'

    App\Tool\Notification\EmailSenderToken: ~

    App\Interface\SendTokenInterface:
        class: App\Tool\Notification\EmailSenderToken

    App\EventListener\ApiRateLimitListener:
        arguments:
            $apiListener: '@limiter.api'
